services:
  backend:
    image: ${APP_NAME}:${IMAGE_TAG}
    container_name: backend
    restart: unless-stopped
    ports:
      - "5000:5000"
    networks:
      - devops-net

networks:
  devops-net:
    name: devops-net
    driver: bridge
